= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/devstack-formula/compare/v1.0.1...v1.0.2++[1.0.2^] (2020-09-27)

=== Documentation

* *pillar.example:* tidyup comments
(https://github.com/saltstack-formulas/devstack-formula/commit/97bf36e7034f9d1322bc98143ebf3680d85983bb[97bf36e^])

=== Styles

* linting for `yamllint`
(https://github.com/saltstack-formulas/devstack-formula/commit/7ba225d6d7833012bddd432e2809fec6774b7b08[7ba225d^])

== link:++https://github.com/saltstack-formulas/devstack-formula/compare/v1.0.0...v1.0.1++[1.0.1^] (2020-09-04)

=== Documentation

* *readme:* fix syntax
(https://github.com/saltstack-formulas/devstack-formula/commit/da697e0053356d314ecbdaf6d71b708cfa1ec737[da697e0^])

== 1.0.0 (2020-09-04)

=== Bug Fixes

* *baseline:* need distutils
(https://github.com/saltstack-formulas/devstack-formula/commit/710ed0bda0cb49144aa95a238ddabd34fbc58c1f[710ed0b^])
* *bug:* workaround hardcoded 127.0.0.1
(https://github.com/saltstack-formulas/devstack-formula/commit/57616810e8b57f07a4598c54686a669cd01d3176[5761681^])
* *centos:* workaround pyyaml error
(https://github.com/saltstack-formulas/devstack-formula/commit/40f8f4ff199bfa5b336edb2f18efbfaa4c463c40[40f8f4f^])
* *centos:* workarounds for centos bugs
(https://github.com/saltstack-formulas/devstack-formula/commit/23a085d62a9da11b67e7617bdfa9554a7b539f10[23a085d^])
* *freebsd:* no package named bridge-utils
(https://github.com/saltstack-formulas/devstack-formula/commit/e0ef84256690363e48079ef1ba82a3f1cfe2dd76[e0ef842^])
* *install:* avoid git proxy issues
(https://github.com/saltstack-formulas/devstack-formula/commit/d3a3876d6775c7948df60dd463ceafdbfc0ab297[d3a3876^])
* *install:* set defaults (per pillar.example) in sls
(https://github.com/saltstack-formulas/devstack-formula/commit/ed5a6cf2517c4bf1db6185123cff86d632ab7b98[ed5a6cf^])
* *install:* typo
(https://github.com/saltstack-formulas/devstack-formula/commit/46ea234df653b0b2fb7467e60066edfb24745c07[46ea234^])
* *jinja:* no ip4_gw grain on FreeBSD
(https://github.com/saltstack-formulas/devstack-formula/commit/6f87855fca7a59fe0bce4ce69f0f72620cfb18bb[6f87855^])
* *ubuntu:* purge simplejson pkg
(https://github.com/saltstack-formulas/devstack-formula/commit/6aa8e3e9a0d136fa684a87633505716d8bcf1013[6aa8e3e^])
* *ubuntu:* purge simplejson pkg
(https://github.com/saltstack-formulas/devstack-formula/commit/2f77409be06f6ffaebc98046055931b330dd22ca[2f77409^])
* *ubuntu:* some fixes
(https://github.com/saltstack-formulas/devstack-formula/commit/60205bfc2b5ee02c91a8e4b07b6b539591ff19f5[60205bf^])

=== Code Refactoring

* *formula:* align to template formula
(https://github.com/saltstack-formulas/devstack-formula/commit/498f07787fbd2ea0bd3aee3eec34eb183ea7e9a5[498f077^])
* *install:* add logfile environment variable
(https://github.com/saltstack-formulas/devstack-formula/commit/25c8bdbe5091b995b69f6ddbded5fb0d2ed79363[25c8bdb^])
* *install:* tested on ubuntu 18.04 server image
(https://github.com/saltstack-formulas/devstack-formula/commit/7fea6f5998a1f9d15166dacff7aeccd85db71239[7fea6f5^])
* *osfinger:* needed for ubuntu18
(https://github.com/saltstack-formulas/devstack-formula/commit/4b5459163f523c35069a039977545da29f9b22e7[4b54591^])
* *template:* use standard map.jinja
(https://github.com/saltstack-formulas/devstack-formula/commit/ff76de039fca50e3491e8ef7a20da61d075ca4e8[ff76de0^])

=== Continuous Integration

* *linters:* fix lint errors, etc
(https://github.com/saltstack-formulas/devstack-formula/commit/86c599bdb1467f6de79421924037567efb3c92f5[86c599b^])

=== Features

* *port:* extra check for port 80
(https://github.com/saltstack-formulas/devstack-formula/commit/aa3ee8d9b847cc5752eaa90ead5dd929c2f4a01e[aa3ee8d^])
